// <auto-generated />
namespace ICEBERG.Datos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Cliente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cliente));
        
        string IMigrationMetadata.Id
        {
            get { return "202306261911563_Cliente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
